---
# tasks file for ssh

# Install Dependencies
- name: Ensure SSH dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ssh_dependencies | list }}"

# Generate SSH Keys
- name: Ensure SSH home directory exists.
  file:
    path: "{{ ssh_home }}/.ssh"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    state: directory
    mode: 0700
  become: true
  become_user: "{{ ssh_user }}"

- name: Check that the user private ssh key exists
  stat:
    path: "{{ ssh_privkey }}"
  register: ssh_private_key_exists

- name: Generate SSH Key
  user:
    name: "{{ ssh_user }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    ssh_key_comment: "{{ ssh_key_comment | default(inventory_hostname) }}"
  become: true
  become_user: "{{ ssh_user }}"
  when: ssh_private_key_exists.stat.exists == false
  register: ssh_key_generated

- name: Ensure the keys have restricted permissions
  file:
    path: "{{ item }}"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: 0600
  with_items:
  - "{{ ssh_privkey }}"
  - "{{ ssh_pubkey }}"

- name: Add local SSH public key to admin account authorized_keys
  authorized_key:
    user: "{{ ssh_user }}"
    key: "{{ lookup('file', ssh_pubkey) }}"
    exclusive: no
    manage_dir: yes
  when: ssh_key_generated.changed

- name: Install SSH agent helper
  copy:
    src: start-agent
    dest: "{{ ssh_home }}/.ssh/start-agent"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: 0600
  when: ssh_key_generated.changed

- name: Start ssh-agent in the background
  shell: eval "$(ssh-agent -s)" && ssh-add {{ ssh_privkey }}
  become: true
  become_user: "{{ ssh_user }}"
  when: ssh_key_generated.changed

# SSH Configuration
- name: "{{ ssh_password_auth | ternary('Allow','Disallow') }} password authentication"
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^PasswordAuthentication" 
    line: "PasswordAuthentication {{ ssh_password_auth | ternary('yes','no') }}" 
    state: present

- name: "{{ ssh_root_login | ternary('Allow','Disallow') }} root SSH access"
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^PermitRootLogin" 
    line: "PermitRootLogin {{ ssh_root_login | ternary('yes','no') }}" 
    state: present

- name: "Ensure SSH is {{ ssh_start | ternary('started','stopped') }}"
  service: 
    name: ssh 
    state: "{{ ssh_start | ternary('restarted','stopped') }}"
    enabled: "{{ ssh_service_enabled }}"
